### PR TITLE
Always use backtick for hash

### PR DESCRIPTION
**Pull request by KentaNo1**

### CODE REVIEW

**Comment by Mathu-lmn** [comment]
Why using backticks ? Is there a specific reason ?

**Comment by KentaNo1** [comment]
You need modelhash when creating a ped or entity, not a name.
See: https://docs.fivem.net/natives/?_0xD49F9B0955C367DE
https://docs.fivem.net/natives/?_0x963D27A58DF860AC

**Comment by Mathu-lmn** [comment]
Yeah this part works either way, but I'm wondering why you're using ` instead of "

**Comment by KentaNo1** [comment]
Because ` returns the modelhash

**Comment by Mathu-lmn** [comment]
didn't even knew that oOOO
I'll merge it

**Pull request merged**
